<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IsPackable>false</IsPackable>

		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<EnableMSTestRunner>true</EnableMSTestRunner>

		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>

		<UseLocalMessageQueueProjectReference>true</UseLocalMessageQueueProjectReference>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Moq" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Ruya.Services.ReliableMessaging\Ruya.Services.ReliableMessaging.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Services.ReliableMessaging.MessageQueue\Ruya.Services.ReliableMessaging.MessageQueue.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Services.MessageQueue\Ruya.Services.MessageQueue.csproj" />
		<ProjectReference
			Include="..\..\src\Ruya.Services.MessageQueue.InMemory\Ruya.Services.MessageQueue.InMemory.csproj"
			AdditionalProperties="UseLocalMessageQueueProjectReference=true" />
	</ItemGroup>

</Project>
