<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Core abstractions and infrastructure for a messaging framework - A modern, provider-agnostic messaging framework for .NET</Description>
		<PackageTags>messaging;rabbitmq;redis;service-bus;pub-sub;event-driven</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Polly" />
		<PackageReference Include="OpenTelemetry.Api" />
	</ItemGroup>

	<ItemGroup>
  	<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  	<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Ruya.Services.MessageQueue.InMemory</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Ruya.Services.MessageQueue.RabbitMq</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>


</Project>
