<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Ruya.AspNetCore.Middleware.Unit.Tests" />
	</ItemGroup>

	<PropertyGroup>
		<Description>ASP.NET Core middleware for adding application environment information to HTTP response headers including version, name, and environment.</Description>
		<PackageTags>aspnetcore, middleware, response-headers, environment</PackageTags>
		<Version>8.2</Version>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Ruya.Extensions.Configuration" />
		<PackageReference Include="Ruya.Primitives" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Ruya.Extensions.Configuration\Ruya.Extensions.Configuration.csproj" />
		<ProjectReference Include="..\Ruya.Primitives\Ruya.Primitives.csproj" />
	</ItemGroup>

</Project>
