<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IsPackable>false</IsPackable>

		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<EnableMSTestRunner>true</EnableMSTestRunner>

		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Testcontainers.MsSql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Ruya.Services.DistributedLock.MsSql\Ruya.Services.DistributedLock.MsSql.csproj" />
	</ItemGroup>

</Project>
