<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Amazon S3 implementation for cloud storage services.</Description>
		<PackageTags>aws, s3, cloud, storage, amazon</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="MimeTypesMap" />
		<PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
	</ItemGroup>

	<ItemGroup Condition=" '$(Configuration)' == 'Release' ">
		<PackageReference Include="Ruya.Services.CloudStorage.Abstractions" />
	</ItemGroup>

	<ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
  	<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<ProjectReference Include="..\Ruya.Services.CloudStorage.Abstractions\Ruya.Services.CloudStorage.Abstractions.csproj" />
	</ItemGroup>

</Project>
