<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>SQL Server-based implementation of the distributed lock manager using sp_getapplock. Provides robust distributed locking for applications with SQL Server infrastructure.</Description>
		<PackageTags>distributed-lock;locking;concurrency;sql-server;database</PackageTags>
		<Version>8.2</Version>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Ruya.Services.DistributedLock" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Ruya.Services.DistributedLock\Ruya.Services.DistributedLock.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
	</ItemGroup>

</Project>
