<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>SQL Server provider implementation (table-based message queue)</Description>
		<PackageTags>messaging;sqlserver;mssql;queue;event-driven</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Ruya.Services.MessageQueue" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Ruya.Services.MessageQueue\Ruya.Services.MessageQueue.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
		<PackageReference Include="Polly" />
	</ItemGroup>

</Project>
