<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IsPackable>false</IsPackable>

		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<EnableMSTestRunner>true</EnableMSTestRunner>

		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="appsettings.Test.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />		
		<PackageReference Include="Testcontainers" />
        <PackageReference Include="AWSSDK.S3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Ruya.Services.CloudStorage.Amazon\Ruya.Services.CloudStorage.Amazon.csproj" />
		<ProjectReference Include="..\Ruya.Services.CloudStorage.Tests.Common\Ruya.Services.CloudStorage.Tests.Common.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Testing.Primitives\Ruya.Testing.Primitives.csproj" />
	</ItemGroup>

</Project>
