<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Extensions for hosting background worker services with advanced scheduling and reliability features.</Description>
		<PackageTags>hosting, background-service, worker, cron, resilience, health-check</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Ruya.Diagnostics.Abstractions" />
		<PackageReference Include="Ruya.Extensions.Configuration" />
		<PackageReference Include="Ruya.Primitives" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Ruya.Diagnostics.Abstractions\Ruya.Diagnostics.Abstractions.csproj" />
		<ProjectReference Include="..\Ruya.Extensions.Configuration\Ruya.Extensions.Configuration.csproj" />
		<ProjectReference Include="..\Ruya.Primitives\Ruya.Primitives.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
		<PackageReference Include="Cronos" />
	</ItemGroup>

</Project>
