<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>XML serialization utilities and extensions.</Description>
		<PackageTags>xml, serialization, utilities</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

</Project>
