<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IsPackable>false</IsPackable>

		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<EnableMSTestRunner>true</EnableMSTestRunner>

		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Ruya.Services.ReliableMessaging\Ruya.Services.ReliableMessaging.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Services.ReliableMessaging.EntityFrameworkCore\Ruya.Services.ReliableMessaging.EntityFrameworkCore.csproj" />
	</ItemGroup>

</Project>
