<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Primitive types and helpers for testing.</Description>
		<PackageTags>testing, primitives, helpers, unit-test</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>

		<!--
	  <IsTestProject>true</IsTestProject>

	  <OutputType>Exe</OutputType>
	  <EnableMSTestRunner>true</EnableMSTestRunner>

	  <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
	  <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

	  <TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	  -->
	</PropertyGroup>

	<!--<ItemGroup>
		<None Update="SampleTest\appsettings.Test.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>-->

	<ItemGroup>
		<Compile Remove="SampleTest\**" />
		<None Include="SampleTest\**" LinkBase="SampleTest" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
	</ItemGroup>

</Project>
