<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>In-memory implementation of the distributed lock manager. Ideal for testing and single-instance applications. Not suitable for distributed scenarios.</Description>
		<PackageTags>distributed-lock;locking;concurrency;in-memory;testing</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Ruya.Services.DistributedLock" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Ruya.Services.DistributedLock\Ruya.Services.DistributedLock.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>

</Project>
