<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>RabbitMQ provider implementation</Description>
		<PackageTags>messaging;rabbitmq;amqp;event-driven</PackageTags>
		<Version>8.1</Version>
	</PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="Ruya.Services.MessageQueue" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\Ruya.Services.MessageQueue\Ruya.Services.MessageQueue.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="RabbitMQ.Client" />

	</ItemGroup>

</Project>
