<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IsPackable>false</IsPackable>

		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<EnableMSTestRunner>true</EnableMSTestRunner>

		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

		<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="MSTest" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Ruya.Services.TokenBroker\Ruya.Services.TokenBroker.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Services.TokenBroker.Client\Ruya.Services.TokenBroker.Client.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Services.TokenBroker.Validation\Ruya.Services.TokenBroker.Validation.csproj" />
		<ProjectReference Include="..\..\src\Ruya.Services.TokenBroker.Abstractions\Ruya.Services.TokenBroker.Abstractions.csproj" />
	</ItemGroup>

</Project>
