name: Ruya.Services.DistributedLock.InMemory

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.DistributedLock]

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Services.DistributedLock.InMemory.yml'
      - 'src/Ruya.Services.DistributedLock.InMemory/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.DistributedLock.InMemory'
      project-path: './src/Ruya.Services.DistributedLock.InMemory/Ruya.Services.DistributedLock.InMemory.csproj'
      test-project-paths: './tests/Ruya.Services.DistributedLock.InMemory.Unit.Tests/Ruya.Services.DistributedLock.InMemory.Unit.Tests.csproj'
      dispatch-event-type: 'Ruya.Services.DistributedLock.InMemory'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
      use-testcontainers: false
    secrets:
      PAT: ${{ secrets.PAT }}  # Required for dispatch (chain builds)
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
