name: Ruya.Primitives

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: []  # No dependencies - this is a base library

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Primitives.yml'
      - 'src/Ruya.Primitives/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Primitives'
      project-path: './src/Ruya.Primitives/Ruya.Primitives.csproj'
      # test-project-paths: './test/Ruya.Primitives.Unit.Tests/Ruya.Primitives.Unit.Tests.csproj'
      dispatch-event-type: 'Ruya.Primitives'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}  # Required for dispatch (chain builds)
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
