name: Ruya.Diagnostics.Abstractions

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: []

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Diagnostics.Abstractions.yml'
      - 'src/Ruya.Diagnostics.Abstractions/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Diagnostics.Abstractions'
      project-path: './src/Ruya.Diagnostics.Abstractions/Ruya.Diagnostics.Abstractions.csproj'
      # test-project-paths:
      dispatch-event-type: 'Ruya.Diagnostics.Abstractions'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
