name: Ruya.Services.ReliableMessaging

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Primitives]

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Services.ReliableMessaging.yml'
      - 'src/Ruya.Services.ReliableMessaging/**'
      - 'tests/Ruya.Services.ReliableMessaging.Unit.Tests/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.ReliableMessaging'
      project-path: './src/Ruya.Services.ReliableMessaging/Ruya.Services.ReliableMessaging.csproj'
      test-project-paths: './tests/Ruya.Services.ReliableMessaging.Unit.Tests/Ruya.Services.ReliableMessaging.Unit.Tests.csproj'
      dispatch-event-type: 'Ruya.Services.ReliableMessaging'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
      use-testcontainers: false
    secrets:
      PAT: ${{ secrets.PAT }}  # Required for dispatch (chain builds)
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
