name: Ruya.Services.ReliableMessaging.EntityFrameworkCore

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.ReliableMessaging]

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.ReliableMessaging.EntityFrameworkCore'
      project-path: './src/Ruya.Services.ReliableMessaging.EntityFrameworkCore/Ruya.Services.ReliableMessaging.EntityFrameworkCore.csproj'
      test-project-paths: './tests/Ruya.Services.ReliableMessaging.EntityFrameworkCore.Integration.Tests/Ruya.Services.ReliableMessaging.EntityFrameworkCore.Integration.Tests.csproj'
      dispatch-event-type: 'Ruya.Services.ReliableMessaging.EntityFrameworkCore'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
      use-testcontainers: true
    secrets:
      PAT: ${{ secrets.PAT }}  # Required for dispatch (chain builds)
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
