name: Ruya.Testing.Primitives

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: []

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Testing.Primitives.yml'
      - 'src/Ruya.Testing.Primitives/**'
      - 'tests/Ruya.Testing.Primitives.Unit.Tests/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Testing.Primitives'
      project-path: './src/Ruya.Testing.Primitives/Ruya.Testing.Primitives.csproj'
      test-project-paths: './tests/Ruya.Testing.Primitives.Unit.Tests/Ruya.Testing.Primitives.Unit.Tests.csproj'
      dispatch-event-type: 'Ruya.Testing.Primitives'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
