name: Ruya.Extensions.Hosting

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Diagnostics.Abstractions, Ruya.Extensions.Configuration, Ruya.Primitives]

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Extensions.Hosting.yml'
      - 'src/Ruya.Extensions.Hosting/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Extensions.Hosting'
      project-path: './src/Ruya.Extensions.Hosting/Ruya.Extensions.Hosting.csproj'
      test-project-paths: './tests/Ruya.Extensions.Hosting.Tests/Ruya.Extensions.Hosting.Unit.Tests.csproj'
      dispatch-event-type: 'Ruya.Extensions.Hosting'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
