name: Ruya.Services.TokenBroker.Validation

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.TokenBroker.Abstractions]

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.TokenBroker.Validation'
      project-path: './src/Ruya.Services.TokenBroker.Validation/Ruya.Services.TokenBroker.Validation.csproj'
      # test-project-paths:
      use-local-tokenbroker-project-references: true
      dispatch-event-type: 'Ruya.Services.TokenBroker.Validation'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
