name: Ruya.Diagnostics.Abstractions

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: []

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Diagnostics.Abstractions'
      project-path: './src/Ruya.Diagnostics.Abstractions/Ruya.Diagnostics.Abstractions.csproj'
      test-project-paths: './tests/Ruya.Diagnostics.Abstractions.Unit.Tests/Ruya.Diagnostics.Abstractions.Unit.Tests.csproj'
      test-configuration: 'Debug'
      dispatch-event-type: 'Ruya.Diagnostics.Abstractions'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
      use-testcontainers: false
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
