name: Ruya.Extensions.Configuration

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: []

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Extensions.Configuration'
      project-path: './src/Ruya.Extensions.Configuration/Ruya.Extensions.Configuration.csproj'
      test-project-paths: './tests/Ruya.Extensions.Configuration.Unit.Tests/Ruya.Extensions.Configuration.Unit.Tests.csproj'
      dispatch-event-type: 'Ruya.Extensions.Configuration'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
