name: Ruya.Services.MessageQueue.RabbitMq

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.MessageQueue]

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.MessageQueue.RabbitMq'
      project-path: './src/Ruya.Services.MessageQueue.RabbitMq/Ruya.Services.MessageQueue.RabbitMq.csproj'
      test-project-paths: |
        ./tests/Ruya.Services.MessageQueue.RabbitMq.Unit.Tests/Ruya.Services.MessageQueue.RabbitMq.Unit.Tests.csproj
        ./tests/Ruya.Services.MessageQueue.RabbitMq.Integration.Tests/Ruya.Services.MessageQueue.RabbitMq.Integration.Tests.csproj
      use-testcontainers: true
      testcontainers-timeout: '1200s'
      dispatch-event-type: 'Ruya.Services.MessageQueue.RabbitMq'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
