name: Ruya.Services.DistributedLock.MsSql

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.DistributedLock]

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.DistributedLock.MsSql'
      project-path: './src/Ruya.Services.DistributedLock.MsSql/Ruya.Services.DistributedLock.MsSql.csproj'
      test-project-paths: './tests/Ruya.Services.DistributedLock.MsSql.Integration.Tests/Ruya.Services.DistributedLock.MsSql.Integration.Tests.csproj'
      test-configuration: 'Debug'
      dispatch-event-type: 'Ruya.Services.DistributedLock.MsSql'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
      use-testcontainers: true
    secrets:
      PAT: ${{ secrets.PAT }}  # Required for dispatch (chain builds)
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
