name: Ruya.Services.CloudStorage.Amazon

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.CloudStorage.Abstractions]

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.CloudStorage.Amazon'
      project-path: './src/Ruya.Services.CloudStorage.Amazon/Ruya.Services.CloudStorage.Amazon.csproj'
      test-project-paths: './tests/Ruya.Services.CloudStorage.Amazon.Integration.Tests/Ruya.Services.CloudStorage.Amazon.Integration.Tests.csproj'
      test-configuration: 'Debug'
      use-testcontainers: true
      testcontainers-timeout: '600s'
      dispatch-event-type: 'Ruya.Services.CloudStorage.Amazon'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
