name: Ruya.Services.MessageQueue.MsSql

on:
  workflow_dispatch:
    inputs:
      rollingDeployment:
        type: boolean
        description: 'Initiate rolling deployment (chain builds)'
        default: false

  repository_dispatch:
    types: [Ruya.Services.MessageQueue]

  push:
    branches: [main, release-preview, release-qa, develop]
    paths:
      - '.github/workflows/Ruya.Services.MessageQueue.MsSql.yml'
      - 'src/Ruya.Services.MessageQueue.MsSql/**'

jobs:
  build:
    uses: ./.github/workflows/dotnet-library-build.yml
    with:
      project-name: 'Ruya.Services.MessageQueue.MsSql'
      project-path: './src/Ruya.Services.MessageQueue.MsSql/Ruya.Services.MessageQueue.MsSql.csproj'
      # test-project-paths:
      dispatch-event-type: 'Ruya.Services.MessageQueue.MsSql'
      triggered-branch: ${{ github.event.client_payload.branch || '' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
